name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install libarchive, libacl and gzip
    - run: sudo apt install libarchive-dev libacl-dev gzip
    - name: make
      run: make
